### ISSUE TITLE
Failure after test cases execute so no artifacts

### ISSUE THREAD

**Issue by jsm174** [webbertakken/unity-test-runner#61]
Hello. 

Using this action, we were able to get test cases for one of the projects I'm helping on to run. Many of the test cases fail, which is to be expected. (Still need to figure out cross platform libraries/dllmaps, etc).

Anyway, after the test cases complete, we get:

```
                <test-suite type="TestFixture" id="1394" name="BumperCollisionTests" fullname="VisualPinball.Unity.Test.VPT.Bumper.BumperCollisionTests" classname="VisualPinball.Unity.Test.VPT.Bumper.BumperCollisionTests" runstate="Runnable" testcasecount="1" result="Passed" start-time="2020-06-27 11:32:42Z" end-time="2020-06-27 11:32:42Z" duration="0.012162" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
                  <properties />
                  <test-case id="1395" name="TestSomething" fullname="VisualPinball.Unity.Test.VPT.Bumper.BumperCollisionTests.TestSomething" methodname="TestSomething" classname="VisualPinball.Unity.Test.VPT.Bumper.BumperCollisionTests" runstate="Runnable" seed="1298413224" result="Passed" start-time="2020-06-27 11:32:42Z" end-time="2020-06-27 11:32:42Z" duration="0.005991" asserts="0">
                    <properties />
                  </test-case>
                </test-suite>
              </test-suite>
            </test-suite>
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>/steps/run_tests.sh: line 157: [: =: unary operator expected
/steps/run_tests.sh: line 175: [: -gt: unary operator expected
##[error]The process '/usr/bin/docker' failed with exit code 2
 Run actions/upload-artifact@v1
```

Even though there are test case errors, shouldn't we still get an artifact with the results xml?

Log: https://github.com/jsm174/vpe_net_standard/runs/813885387?check_suite_focus=true#step:4:13059
Workflow: https://github.com/jsm174/vpe_net_standard/blob/unity-workflow-3/.github/workflows/main.yml

**Comment by webbertakken** [comment]
Hi @jsm174 and thank you for posting about your issue with Test-runner.

So you are getting the artifact as you expected, it's just that in your workflow it doesn't upload it because the upload job never runs:

![image](https://user-images.githubusercontent.com/20756439/85923459-7e784e80-b88b-11ea-9a4b-cca52ac04c45.png)

See Github Actions [docs](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions) for conditional job to solve your issue.

**Comment by jsm174** [comment]
Thank you. I apologize. I didn't really think about that since I was just following the example.

I did add and if condition, but it's still failing. I'll need to research it some more. 

```
 - uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
```

![Screen Shot 2020-06-27 at 11 22 59 AM](https://user-images.githubusercontent.com/1197137/85925812-fed98800-b868-11ea-8114-6c93fc51974a.png)

**Comment by webbertakken** [comment]
After you added the if condition, the upload job started triggering when the test job failed, as expected.

Currently you need to correctly configure `path` 

![image](https://user-images.githubusercontent.com/20756439/85926461-ed5fa280-b89f-11ea-9d6a-0a8cb30707d0.png)

There is a working example of this in the readme and in the workflow of this repository.

**Comment by jsm174** [comment]
I did follow all your documentation.  

So just to make sure I'm not crazy, I just made the file match up exactly with the one from your repo:

https://github.com/jsm174/vpe_net_standard/blob/48e6c4a6e2773c58b16c265502882d1c9930fbb9/.github/workflows/main.yml

Same error

https://github.com/jsm174/vpe_net_standard/runs/814289122?check_suite_focus=true

**Comment by webbertakken** [comment]
Great! Then you should be close to getting it working, because the docs seem to work for everyone.

>  I just made the file match up exactly with the one from your repo:

With the two major differences that your project path is both nested and considered hidden within Unity. 

As discussed [here](https://github.com/webbertakken/unity-test-runner/issues/62) in your other issue, using temporary or hidden folders as your project folder is not supported in Unity itself, so it will also be impossible to support it in this project.

The workflow from this repository also does not take those two things into account, so naturally it wouldn't work out of the box.

I will close this issue as both your questions have been answered, but please feel free to create a new ticket if you find that there is indeed something broken in Test runner.

**Comment by jsm174** [comment]
Sounds good. Thanks!

I will create a separate repo that pulls everything in with the correct directory structure and see what happens.
